CREATE TABLE IF NOT EXISTS users (
    id INT AUTO INCREMENT PRIMARY KEY 
    employee_id VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    role ENUM('employee','hr_manager') NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
